CHANGELOG.md
e2e/pull/pull.go
e2e/pull/regressions.go
internal/pkg/client/progress.go

- sylabs/singularity# 1088
which fixed
- sylabs/singularity# 1087
> When an http(s) pull doesn't provide a content-length header, we need to ensure the progress bar completes. If we don't do this, the CLI hangs indefinitely.

fix: don't freeze for http(s) pull without content-length, from sylabs 1088

---

cmd/internal/cli/actions.go
internal/pkg/runtime/launcher/launcher.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/options.go
internal/pkg/runtime/launcher/util.go

- sylabs/singularity# 1039
which fixed
- sylabs/singularity# 1021
> Refactor the existing code so that:
> 
> * The internal/pkg/runtime/launcher package contains common option handling, utility functions, and a Launcher interface.
> 
> * There is a launcher.native package containing the existing launch code for the native singularity runtime.
> 
> 
> Add placeholder OCI launcher
> 
> * Accepts no options, fails if options provided.
> 
> * Implements an Exec method which does nothing.

launcher: refactor and add OCI placeholder launcher, from sylabs 1039

---

cmd/internal/cli/action_flags.go
cmd/internal/cli/actions.go
e2e/actions/actions.go
e2e/internal/e2e/apptainercmd.go
e2e/internal/e2e/profile.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1042
which fixed
- sylabs/singularity# 1022
> Depends on sylabs/singularity# 1021
> 
> Add an `--oci` flag to actions (run/shell/exec) that calls the (no-op) OCI launcher instead of the singularity native runtime launcher.
> 
> Fix OCI launcher supported option checks for empty structs (not just nils), and always set options.
> 
> Add E2E profiles and a test for unimplemented error on the --oci option.

actions: Add --oci flag to call OCI launcher, from sylabs 1042

---

.github/workflows/ci.yml
CHANGELOG.md
cmd/internal/cli/actions.go
cmd/internal/cli/checkpoint.go
cmd/internal/cli/instance_start_linux.go
cmd/internal/cli/startvm.go
e2e/actions/actions.go
e2e/actions/oci.go
e2e/oci/oci.go
internal/pkg/runtime/launcher/launcher.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/oci/oci_conmon_linux.go
internal/pkg/runtime/launcher/oci/oci_linux.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go
internal/pkg/util/bin/bin.go

- sylabs/singularity# 1093
which fixed
- sylabs/singularity# 598
> As a first step toward run/shell/exec actions on native OCI images, implement a minimal `singularity run --oci mybundle` which:
> 
> * Requires an on-disk bundle with appropriate `config.json`.
> * Runs this bundle using `crun` or `runc`.
> * Makes no attempt to handle any arguments or options.
> * Does not modify the `config.json` - i.e. it must match namespace / mapping requirements for rootless execution etc.
> 
> At this stage, the functionality is essentially equivalent to `singularity oci run` and is not yet useful.
> 
> The primary purpose of the PR is to refactor some of the code that passes args for launching a container.
> 
> In addition, we now use `crun` …

feat: run action for OCI bundle, from sylabs 1093

---

cmd/internal/cli/actions.go
cmd/internal/cli/oci_linux.go
e2e/actions/oci.go
internal/app/apptainer/oci_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
pkg/ocibundle/bundle.go
pkg/ocibundle/native/bundle_linux.go
pkg/ocibundle/native/bundle_linux_test.go
pkg/ocibundle/sif/bundle_linux.go
pkg/ocibundle/sif/bundle_linux_test.go

- sylabs/singularity# 1125
which fixed
- sylabs/singularity# 1036
> When running containers in `--oci` mode, the argument to run is now an image reference corresponding to a native OCI format handled by containers/image, i.e.
> 
> * docker://
> * docker-archive:
> * docker-daemon:
> * oci-archive:
> * oci:
> 
> The source image is extracted into a temporary OCI bundle, with a minimally valid configuration that:
> 
> * Runs the process specified by CMD & ENTRYPOINT only.
> * Sets the environment specified by the image ENV only.
> 
> 
> The approach is very naive - we pull through Singularity's OCI blob cache into a temporary oci layout dir, before creating the bundle from it. Auth handling for registries is not yet wired up. There is …

feat: run OCI image sources via temporary bundle, from sylabs 1125

---

INSTALL.md
cmd/internal/cli/actions.go
cmd/internal/cli/build_linux.go
dist/debian/control
dist/rpm/apptainer.rpmlintrc
dist/rpm/apptainer.spec.in
e2e/actions/actions.go
e2e/actions/oci.go
internal/app/apptainer/overlay_create.go
internal/pkg/build/stage.go
internal/pkg/fakefake/fakefake.go
internal/pkg/runtime/engine/apptainer/prepare_linux.go
internal/pkg/runtime/engine/apptainer/process_linux.go
internal/pkg/runtime/launcher/launcher.go
internal/pkg/runtime/launcher/native/launcher_linux.go
pkg/ocibundle/native/bundle_linux.go
scripts/ci-deb-build-test

This pulls in sylabs PRs
- sylabs/singularity# 1133
- sylabs/singularity# 1143
- sylabs/singularity# 1145
which fixed
- sylabs/singularity# 1025
- sylabs/singularity# 1041
- sylabs/singularity# 1042
- sylabs/singularity# 1044
The original PR descriptions were:
> Enable `singularity shell --oci ...` with behavior matching native runtime, i.e.
> 
> * Run shell set with SINGULARITY_SHELL or --shell 
> * If not set, try /bin/bash --norc 
> * If not available, use /bin/sh
> Tidy up the rpm spec file.
> * Remove the manual handling of build root, GOPATH etc. Not needed as we are using go modules now.
> * Remove redundant explicit deps.
> * Fix crun -> runc dep for EL7, SLES.
> * Use rpm make_xxx macros instead of direct make calls.
> * Ensure all directories created are owned by package.
> If …

feat: enable shell for --oci mode, from sylabs 1133 & 1143 & 1145

---

e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/spec_linux.go
pkg/ocibundle/native/bundle_linux.go

- sylabs/singularity# 1134
> Move ID mapping and process setup code to the launcher, out of the oci bundle package.
> Add a minimal config for `--oci` mode, rather than starting with the default OCI config.
> Add explicit configuration of mounts, with `tmpfs` mount locations matching the native runtime with `--containall / --compat`.
> Ensure ID mapping is always explicit (including for root).

oci: move some code to launcher, use explicit config, from sylabs 1134

---

cmd/internal/cli/oci_linux.go
e2e/actions/oci.go
internal/pkg/runtime/engine/fakeroot/config/config.go
internal/pkg/runtime/engine/fakeroot/engine_linux.go
internal/pkg/runtime/launcher/oci/README.md
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/oci_conmon_linux.go
internal/pkg/runtime/launcher/oci/oci_linux.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/spec_linux.go
internal/pkg/util/starter/starter.go

- sylabs/singularity# 1135
which fixed
- sylabs/singularity# 1035
> Implements initial --fakeroot support for --oci mode. Mirrors behavior with --compat / --contain.
> 
> The process of accomplishing this is fairly complex. In theory, we should be able to call `crun` directly from host namespaces. We can let `crun` create a default userns and user mapping, or be able to request arbitrary explicit uid mappings (permitted by /etc/subuid /etc/subgid) to be applied.
> 
> Unfortunately this can hit bugs as this path is not well tested in `crun`. See e.g.
> 
> - containers/crun# 1077
> - containers/crun# 1072 
> 
> To avoid requiring the very latest `crun` with fixes, instead move to creating a userns ourselves, with a 'fakeroot' ID …

oci: Add --fakeroot support to --oci mode, from sylabs 1135

---

CHANGELOG.md
etc/conf/testdata/test_1.out.correct
etc/conf/testdata/test_2.in
etc/conf/testdata/test_2.out.correct
etc/conf/testdata/test_3.in
etc/conf/testdata/test_3.out.correct
etc/conf/testdata/test_default.tmpl
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
pkg/util/apptainerconf/config.go

- sylabs/singularity# 1151
which fixed
- sylabs/singularity# 1140
> Use the configuration file sessiondir max size value for --oci mode tmpfs mounts.
>
> Increase the default from 16M -> 64M. The 16M default is very low, and has periodically caused issues running programs that create even small amounts of temporary data on --contained filesystems.

fix: use conf file value for oci tmpfs size, from sylabs 1151

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/oci/spec_linux.go
internal/pkg/runtime/launcher/oci/spec_linux_test.go

- sylabs/singularity# 1157
which fixed
- sylabs/singularity# 1026
> Support namespace request CLI options.
> 
> * --ipc - no effect, always used in --oci mode.
> * --net - only supported with --network none.
> * --pid - no effect, always used in --oci mode.
> * -u / --userns - only effective for root, non-root always uses user ns.
> * --uts
> 
> Add info logging where the option is redundant.

feat: oci: support namespace flags, from sylabs 1157

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/checkpoint/dmtcp/checkpoint.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux_test.go
pkg/runtime/engine/apptainer/config/config.go
pkg/util/bind/bind.go
pkg/util/bind/bind_test.go
pkg/util/bind/mount.go
pkg/util/bind/mount_test.go

- sylabs/singularity# 1158
which fixed
- sylabs/singularity# 1027
- sylabs/singularity# 1028
> Implement support for bind mounts (rw & ro) specified using -B/--bind and --mount on the singularity command line.

feat: oci: enable bind mounts via --bind, --mount, from sylabs 1158

---

e2e/env/env.go
e2e/env/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go

- sylabs/singularity# 1169
which fixed
- sylabs/singularity# 1031
> Pass SINGULARITYENV_ prefixed environment variables into container in --oci mode.

feat: oci: add APPTAINERENV_ handling for --oci mode, from sylabs 1169

---

e2e/env/env.go
e2e/env/oci.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go

- sylabs/singularity# 1170
which fixed
- sylabs/singularity# 1030
> Allow --env-file to be used to provide environment variables in a file, when running a container in --oci mode.
> 
> We use the same approach as the native runtime for compatibility. The env file is evaluated in the embedded shell interpreter, but starting with an empty environment. This handles quoting, comments etc. for us, and keeps maximum compatibility with the existing handling.

feat: oci: enable --env-file in --oci mode, from sylabs 1170

---

CHANGELOG.md

- sylabs/singularity# 1176
> Now that sufficient functionality is in place for `--oci` mode, add a CHANGELOG entry for the current state.

doc: Add CHANGELOG entry for --oci, from sylabs 1176

---

internal/pkg/build/oci/oci.go
pkg/ocibundle/native/bundle_linux.go

This pulls in sylabs part of PR
- sylabs/singularity# 1222
which fixed
- sylabs/singularity# 1221
> When the cache is enabled, and `--oci` mode is used, extract the image directly from the cache oci-layout, rather than copying into a temporary oci-layout first.
> 
> In addition, within the transparent caching functions, check if an image manifest is present before performing a copy into the cache. Although the copy is effectively a no-op if the image is present, this avoids some overhead.

oci: Use cache more efficiently for --oci mode, from sylabs 1222

---

CHANGELOG.md
e2e/gpu/gpu.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

- sylabs/singularity# 1181
which fixed
- sylabs/singularity# 1034
> A selection of ROCm fixes and addition of --oci support. Am including all in a single PR to minimize amount of work needed testing on a ROCm enabled system.
> 
> * In `--oci` mode ensure user and group entries written to container passwd / group files. Required to proceed with ROCm stuff. 
> * When binding ROCm devices with --contain in effect, we were only taking /dev/dri/cardxxx and /dev/kfd. At least some circumstances also require /dev/dri. Bind the whole of /dev/dri, just like the AMD ROCm container documentation for Docker does.
> * Under --oci mode, allow --rocm, which will bind ROCm devices, libraries, and binaries into the container.
> * e2e: minimal --rocm …

rocm: fixups and --oci support, from sylabs 1181

---

CHANGELOG.md
e2e/gpu/gpu.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

- sylabs/singularity# 1207
which fixed
- sylabs/singularity# 1033
> oci: support legacy --nv bind mode

feat: oci: support legacy --nv bind mode, from sylabs 1207

---

e2e/docker/docker.go
e2e/docker/regressions.go
e2e/internal/e2e/profile.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1287
which fixed
- sylabs/singularity# 1286
> In the --oci launcher, When a minimal container doesn't have an `/etc/passwd` or `/etc/groups` file then don't fail with a fatal error. Instead warn like the native runtime does.

fix: lack of passwd / group should be warning in --oci mode, from sylabs 1287

---

cmd/internal/cli/actions.go
e2e/docker/docker.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/options.go

- sylabs/singularity# 1233
which fixed
- sylabs/singularity# 1220
> Honour the DOCKER_HOST, `--no-https`, and auth configuration in `--oci` mode.

oci: pass in SystemContext for image handling, from sylabs 1233

---

CHANGELOG.md
internal/pkg/runtime/engine/apptainer/container_linux.go
internal/pkg/runtime/launch/launcher_linux.go

- sylabs/singularity# 1355
which fixed
- sylabs/singularity# 1352
> Due to incorrect logic / ordering of checks in prepareNetworkSetup, the combination of `--fakeroot --net --network=fakeroot` generated a false error stating that the fakeroot network was not permitted.
> 
> However, execution continued, and the fakeroot network was (correctly) used.
> 
> This is a minimal PR to correct the ordering of checks, such that `--fakeroot --net --network=fakeroot` doesn't give a false error.
> 
> The code handling checks for permitted networks is messy, and still needs a proper refactor. There is overriding of the `--network` setting for `--fakeroot` in the CLI->launcher layer as well, due to way in which the default network is implemented, …

fix: avoid incorrect error with --fakeroot --net --network=fakeroot, from sylabs 1355

---

internal/pkg/runtime/launcher/oci/oci_linux.go

- sylabs/singularity# 1426
which fixed
- sylabs/singularity# 1425
> Drop the warning that not all OCI functionality is supported with runc.
> 
> Some things turned out to be SingularityCE bugs. Some things are very version specific. A new enough runc will work.

oci: drop warning about runc functionality, from sylabs 1426

---

dist/rpm/apptainer.spec.in

- sylabs/singularity# 1456
which fixed
- sylabs/singularity# 1453
> * On SLES we intend to require runc, not crun.
> * squashfs had a duplicate Requires, instead of a BuildRequires.

rpm: fix: correct BuildRequires/Requires for SLES, from sylabs 1456

---

e2e/actions/oci.go
e2e/cgroups/cgroups.go
e2e/env/oci.go
e2e/internal/e2e/env.go
e2e/internal/e2e/image.go
e2e/suite.go

- sylabs/singularity# 1368
which fixed
- sylabs/singularity# 1364
> Fetch the OCI archive image used in tests from Docker Hub, so that it will match the host architecture.

e2e: refactor test image handling, from sylabs 1368

---

.gitignore
CHANGELOG.md
LICENSE_DEPENDENCIES.md
cmd/internal/cli/action_flags.go
cmd/internal/cli/actions.go
e2e/actions/actions.go
e2e/actions/oci.go
go.mod
go.sum
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/cdi_linux.go
internal/pkg/runtime/launcher/oci/cdi_linux_test.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/spec_linux.go
internal/pkg/runtime/launcher/options.go
test/cdi/cditemplate.json.tpl
test/cdi/kmsg.json
test/cdi/tmpmount.json

- sylabs/singularity# 1459
which fixed
- sylabs/singularity# 1394
> Added a `--device` flag to the experimental `--oci` runtime mode, allowing the user to make a device available in the contained using a CDI configuration.

oci: implemented CDI device mapping, from sylabs 1459

---

CHANGELOG.md
cmd/internal/cli/action_flags.go
cmd/internal/cli/actions.go
e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1495
which fixed
- sylabs/singularity# 1474
> Support `--hostname` in OCI mode. Requires UTS namespace, so in OCI mode, `--hostname` will infer `--uts`. Added test in e2e-test suite (e2e/actions/oci.go:148) for this functionality.

oci: support --hostname, from sylabs 1495

---

CHANGELOG.md
e2e/actions/actions.go
e2e/actions/oci.go
e2e/internal/e2e/apptainercmd.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1500
which fixed
- sylabs/singularity# 1473
> Adds support for `--home` in OCI mode.
> 
> Specifically, supplying a single location (e.g. `--home /myhomedir`) will result in a new tmpfs directory being created at the specified location inside the container, and that dir being set as the in-container user's home dir. Supplying two locations separated by a colon (e.g. `--home /home/user:/myhomedir`) will result in the first location on the host being bind-mounted as the second location in-container, and set as the in-container user's home dir.
> ### Testing notes
> 
> Added e2e tests in e2e/actions/oci.go to largely mirror how we test the corresponding native-mode functionality, with the caveat that the tests now …

oci: support --home, from sylabs 1500

---

CHANGELOG.md
e2e/actions/oci.go

- sylabs/singularity# 1503
The original PR description was: 
> Some really minor stuff that I neglected to include in PR sylabs/singularity# 1394:
> * Adding `--cdi-dirs` (with explanation) to CHANGELOG.md
> * Better commenting on the new code in `actionOciCdi()` in e2e/actions/oci.go

Minor improvements to cdi support in oci, from sylabs 1503

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/util/fs/helper.go
internal/pkg/util/fs/helper_linux_test.go

- sylabs/singularity# 1518
which fixed
- sylabs/singularity# 1517
> When running in --oci mode as a normal user, Singularity sets up an outer userns that provides an unprivileged root. When --fakeroot is not also requested, runc / crun then map back to the user's own uid/gid via an inner reverse mapping specified in config.json.
> 
> This mapping was not being applied correctly, as a userns was not requested in the config.json for all situations where a reverse mapping was requested.
> 
> Ensure that if we specify a mapping in config.json then we request a userns so that it is applied.
> 
> Cover this behavior in an e2e-test by writing to a host dir from the container, and checking ownership of the file on the host.

fix: oci: explicitly request userns for inner reverse idmap, from sylabs 1518

---

internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go

- sylabs/singularity# 1537
which fixed
- sylabs/singularity# 1519
> In `getReverseUserMaps`,we were taking `targetUID` and `targetGID` parameters that define the UID and GID the container will be entereed as. However, the mappings returned were based on the current host UID and GID, and not the target IDs.
> 
> Ensure that the user maps use the `targetUID` and `targetGID`.
> 
> Split the function up so that the core computation of the user maps can be tested. The tests help to explain what the intended functionality here is... which is beneficial as it's somewhat complex.

fix: oci: reverse uid/gid maps now honour target IDs, from sylabs 1537

---

internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1539
which fixed
- sylabs/singularity# 1538
> When executed from a root-owned cgroup, such as the session scope resulting from a bare ssh login, crun will fail to create our requested container cgroup.
> 
> If we are running as non-root, create and move into a user-owned cgroup, so that there's a common user-owned ancestor. This avoids the `crun` error.
> 
> Note that no workaround is needed for `runc` as it is able to create the requested container cgroup without any issue.

fix: oci: enter cgroup before executing crun as non-root, from sylabs 1539

---

e2e/docker/docker.go
e2e/docker/regressions.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1553
which fixed
- sylabs/singularity# 1528
> Pass host's `TERM` environment variable to container in OCI mode. Can be overridden by setting `SINGULARITYENV_TERM` on host.

fix: TERM not set in OCI containers, from sylabs 1553

---

CHANGELOG.md
e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1551
which fixed
- sylabs/singularity# 1472
> Brought handling of `resolv.conf` and `--dns` flag in OCI mode on par with their behavior in native mode.
> 
> In particular: an `/etc/resolv.conf` file is always created in the OCI container. If a `--dns` argument is provided, its contents (a comma-separated list of IPs of nameservers) determines the content of this `resolv.conf` file. Otherwise, the content is taken from the host's `/etc/resolv.conf` file.

oci: support resolv.conf and --dns, from sylabs 1551

---

LICENSE_DEPENDENCIES.md
internal/pkg/runtime/launcher/oci/cdi_linux_test.go
pkg/util/slice/slice.go
pkg/util/slice/slice_test.go

- sylabs/singularity# 1562
which fixed
- sylabs/singularity# 1485
> Now that we can safely assume Go 1.18+ (see [here](https://github.com/sylabs/singularity/issues/1485#issuecomment-1503000209)), I have moved a [`lo`](https://github.com/samber/lo)-based utility function (`HashingListSubtract()`) that was buried inside the test code into a more general-purpose utility package.

pull HashingListSubtract into (new) high-level util package, from sylabs 1562

---

internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1566
> Fixes a tiny typo ("resolve.conf" -> "resolv.conf") in warning message in internal/pkg/runtime/launcher/oci/launcher_linux.go:393

fixed typo (resolve.conf -> resolv.conf), from sylabs 1566

---

internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1570
which fixed
- sylabs/singularity# 1569
> If we are running under cgroups v1 or with the cgroupfs manager (i.e. not systemd as cgroup manager), do not attempt to enter a cgroup at startup with crun. We cannot create a cgroup unprivileged in this situation.
> 
> Under cgroups v1, crun will not perform the cgroups manipulation that leads to the issue we worked around in sylabs/singularity# 1539. Any other issue with the cgroup that we are in at launch cannot be rectified, either.

fix: oci: Don't create cgroup for crun on v1 / cgroupfs, from sylabs 1570

---

e2e/docker/docker.go
e2e/docker/regressions.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1588
which fixed
- sylabs/singularity# 1586
> When we run a container in `--oci` mode, we have a temporary rootfs that must be removed when the container exits.
> 
> A container can contain files / dirs with restrictive permissions that prevent direct removal.
> 
> Use fs.ForceRemoveAll, which will chmod & remove anything that os.RemoveAll is unable to remove.

fix: Remove files with restrictive perms from --oci temp rootfs, from sylabs 1588

---

e2e/actions/oci.go

- sylabs/singularity# 1496
which fixed
- sylabs/singularity# 1481
> 1. Support `--pwd` in OCI mode.
> 2. Replace `--pwd` with `--cwd` (see comments by @ dtrudg on [Support `--pwd` in `--oci` mode # 1481](https://github.com/sylabs/singularity/issues/ 1481)), and adjust code throughout to reflect this (i.e., misleading references to "{p,P}wd" in the code replaced with "{c,C}wd"). Keep `--pwd` flag as a synonym, for backwards compatibility.

1481 support pwd in oci mode, from sylabs 1496

---

e2e/actions/oci.go
e2e/suite.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1523
> There was a problem where, in OCI mode, a custom working directory (`--cwd`/`--pwd`) would not be respected, and the homedir would be used as the working directory instead.
> 
> Interestingly, this was not caught by our e2e tests, which (ultimately) revealed a problem in the way I was handling profiles in the `actionOciExec()` function (e2e/actions/oci.go:228).
> 
> This fixes both issues.

oci: fix custom cwd not respected when homedir set, from sylabs 1523

---

e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1530
which fixed
- sylabs/singularity# 1529
> Fix `--home` functionality in OCI-mode, so it works even when running as root (e.g. under `sudo`) or when running with `--fakeroot`.

oci: fix --home when running as root or fakeroot, from sylabs 1530

---

e2e/docker/docker.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1594
which fixed
- sylabs/singularity# 1593
> In OCI mode, avoid overriding container's HOME environment variable if container specifies its own USER.
> 
> Also add e2e test of the above.

oci: fix to not override HOME when container specifies USER (+ e2e test), from sylabs 1594

---

CHANGELOG.md
cmd/internal/cli/oci_linux.go
docs/content.go
e2e/actions/actions.go
e2e/actions/oci.go
e2e/docker/docker.go
e2e/docker/regressions.go
e2e/imgbuild/imgbuild.go
e2e/suite.go
internal/app/apptainer/oci_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/oci_overlay.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go
internal/pkg/runtime/launcher/options.go
pkg/ocibundle/tools/overlay_linux.go

- sylabs/singularity# 1659
which fixed
- sylabs/singularity# 1478
> Support `--overlay <overlay_dir>` flag in OCI-mode (in "action" commands, i.e., run/exec/shell). This allows the user to mount a directory as a filesystem overlay, in lieu of using a writable tmpfs (which is the default behavior since version 3.11.3). This enables writes to the filesystem to persist across runs of the OCI container. If `<overlay_dir>` does not exist, Singularity will attempt to create it.

oci: support --overlay, from sylabs 1659

---

CHANGELOG.md
cmd/internal/cli/action_flags.go
e2e/actions/actions.go
e2e/actions/common.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

- sylabs/singularity# 1689
which fixed
- sylabs/singularity# 1483
> Provides support for `--workdir` in OCI-mode.
> 
> Specifying `--workdir <dir>` means that `/tmp` and `/var/tmp` will be mapped, respectively, to `<workdir>/tmp` and `<workdir>/var_tmp` on the host, rather than to tmpfs storage. If `--scratch <scratchdir>` is used in conjunction with `--workdir`, scratch directories will be mapped to subdirectories nested under `<workdir>/scratch` on the host, rather than to tmpfs storage. (This is line with the behavior of `--scratch` in conjunction with `--workdir` in native mode.)
> 
> Also changed the usage string for the `--workdir` option to make it clear that $HOME is unaffected by this option. (The latter can be manipulated …

oci: support --workdir, from sylabs 1689

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go

- sylabs/singularity# 1714
which fixed
- sylabs/singularity# 1712
> When runc/crun is called from oci_runc_linux.go, Stdin was incorrectly connected for the various runc/crun operations.
> 
> * Non-interactive operations such as resume / kill don't need Stdin.
> * Interactive operations (run/exec) had cmd.Stdin incorrectly set to os.Stdout. This prevented OCI containers from receiving input from pipes, redirection, etc.
> 
> 
> This PR fixes these issues and ports action STDPIPE tests to --oci mode. These were previously missed, resulting in sylabs/singularity# 1712 not being caught by the e2e suite.

fix: correct Stdin wire-up in runc/crun execs, from sylabs 1714

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

- sylabs/singularity# 1694
which fixed
- sylabs/singularity# 1693
> Fixes a bug where `--scratch` failed when used in conjunction with `--workdir` if the latter was given a relative (rather than absolute) path.
> 
> Also changes the behavior of `--workdir` code so that an error (rather than a warning) is generated if specified workdir cannot be converted to an absolute path.
> 
> Lastly, adds e2e tests for this behavior (`--scratch` in conjunction with relative `--workdir`), in both native and OCI modes.

fix rel. path --workdir with --scratch, add oci e2e tests, from sylabs 1694

---

cmd/internal/cli/actions.go
cmd/internal/cli/build_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/oci_linux.go
internal/pkg/runtime/launcher/oci/oci_overlay.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go
internal/pkg/runtime/launcher/oci/spec_linux.go
internal/pkg/runtime/launcher/oci/spec_linux_test.go
internal/pkg/runtime/launcher/options.go
internal/pkg/util/fs/overlay/overlay_linux.go
internal/pkg/util/fs/overlay/overlay_linux_test.go
internal/pkg/util/rootless/rootless.go
internal/pkg/util/rootless/rootless_test.go
pkg/syfs/syfs.go

- sylabs/singularity# 1774
which fixed
- sylabs/singularity# 1773
> Before this PR, if we are a non-root user we enter a root-mapped user namespace before calling `singularity oci run` at the end of the `--oci` launcher flow. If we are the root user, we do not enter any namespace. This means that bundle preparation, performed by the launcher, takes place outside of any namespaces.
> 
> As a non-root user, we want to perform bundle preparation inside a root-mapped user namespace. This is in order to benefit from fully-unprivileged FUSE operations when we start handling image mounts, plus advantages around cleanup on namespace exit. As a root user, we want to be inside a mount namespace to avoid polluting the host mount namespace with …

Enter namespaces earlier in --oci mode, from sylabs 1774

---

CHANGELOG.md
e2e/actions/oci.go
e2e/config/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1784
which fixed
- sylabs/singularity# 1783
- sylabs/singularity# 1780
> **fix: set correct $HOME in --oci mode when mount home = no**
> 
> When `mount home = no` is set in `singularity.conf`, we still need to set the correct value for `$HOME` in the container... we just don't want to mount it.
> 
> **support `--no-home` in `--oci` mode**
> 
> When `--no-home` is set on the CLI in `--oci` mode, do not mount onto the container home directory.

fix `mount home=no`, support `--no-home` in `--oci` mode, from sylabs 1784

---

CHANGELOG.md
e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

- sylabs/singularity# 1785
which fixed
- sylabs/singularity# 1781
> Allow the `--no-mount` flag to be specified in `--oci` mode. This allows disabling the following mounts:
> 
>  * proc
>  * sys
>  * devpts
>  * tmp
>  * home
> 
> Note that `dev` cannot be supported in `--oci` mode, as an OCI runtime _requires_ that certain devices are present, and will include them in a `/dev` tmpfs.
> 
> We currently run similar to native mode `--compat`, so we don't mount the current working directory. Therefore, `--no-mount cwd` is not supported.
> 
> Similarly, `--compat` infers that `bind path` entries from `singularity.conf` are ignored. We may handle them in some way, in future.

oci: Support --no-mount, to extent possible, from sylabs 1785

---

CHANGELOG.md
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux_test.go

- sylabs/singularity# 1786
which fixed
- sylabs/singularity# 1782
> Support the hidden `--containlibs` flag, and its env var `SINGULARITY_CONTAINLIBS` in `--oci` mode.
> 
> Specified paths are bound into `/.singularity.d/libs` in the container, which is on the container `LD_LIBRARY_PATH`.

oci: support --containlibs / SINGULARITY_CONTAINLIBS, from sylabs 1786

---

e2e/actions/actions.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1792
which fixed
- sylabs/singularity# 17891
> In the refactoring performed in [a10b379](https://github.com/sylabs/singularity/commit/a10b379bf8859ee35abca55f31a3576f202df792), the setting of the default CWD, and creation of `/etc/passwd`, was not correctly adapted.
> 
> We need to use our parsed / processed `l.homeDest` value for the container homeDir in all cases. With a nested root-mapped user namespace re-exec, the CLI passed value is not correct unless it is a custom value.
> 
> The first commit adds e2e coverage for this issue. The second commit is the fix.

fix: oci: correct $HOME -> default cwd / passwd handling, from sylabs 1792

---

CHANGELOG.md
e2e/security/oci.go
e2e/security/security.go
internal/pkg/confgen/testdata/test_1.out.correct
internal/pkg/confgen/testdata/test_2.in
internal/pkg/confgen/testdata/test_2.out.correct
internal/pkg/confgen/testdata/test_3.in
internal/pkg/confgen/testdata/test_3.out.correct
internal/pkg/confgen/testdata/test_default.tmpl
internal/pkg/runtime/engine/config/oci/config.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/spec_linux.go
pkg/util/apptainerconf/config.go

- sylabs/singularity# 1798
which fixed
- sylabs/singularity# 1587
> ### Preparatory commit, for consistency:
> 
> **oci: Don't set inheritable/ambient caps in DefaultConfig**
> 
> The OCI DefaultConfig, used when creating a bundle from a SIF via `singularity oci mount`, no longer sets any inheritable or ambient capabilities. This matches other OCI container runtimes.
> 
> The capability set matches: https://github.com/opencontainers/runc/blob/main/libcontainer/SPEC.md#security
> ### Implementation commit in --oci mode:
> 
> **oci: set default capabilities in --oci mode**
> 
> When running in `--oci` mode, set default capabilities for the container.
> 
> When root inside the container, this means that effective / permitted / bounding …

oci: wire up default capabilities, from sylabs 1798

---

CHANGELOG.md
cmd/internal/cli/action_flags.go
e2e/security/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go

- sylabs/singularity# 1800
which fixed
- sylabs/singularity# 1477
> When `--no-privs` is set on the command line:
> 
>  * The container process capability set should be empty.
>  * NoNewPrivileges should be enabled for the container process.

oci: Support --no-privs, from sylabs 1800

---

CHANGELOG.md
e2e/security/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
pkg/util/capabilities/capabilities.go
pkg/util/capabilities/capabilities_test.go
pkg/util/capabilities/process_linux.go

- sylabs/singularity# 1803
which fixed
- sylabs/singularity# 1475
> When `--keep-privs` is specified in `--oci` mode, keep effective capabilities on the container process, rather than set the default OCI capabilities.
> 
> Non-root users in the container receive the capabilities in the bounding set only.

oci: support --keep-privs

---

CHANGELOG.md
e2e/security/oci.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go

- sylabs/singularity# 1804
which fixed
- sylabs/singularity# 1468
> Add support for --add-caps and --drop-caps to modify the capabilities of the container process.
> 
> When the container user is root, these modify the permitted/effective/bounding sets.
> 
> When the container user is non-root, the bounding set is modified, and any explicit add-caps are added to the permitted/effective/inheritable/ambient sets.

oci: Support --add-caps and --drop-caps, from sylabs 1804

---

internal/pkg/build/oci/fetch.go
internal/pkg/build/oci/oci.go
internal/pkg/build/oci/unpack.go
internal/pkg/build/sources/conveyorPacker_oci.go
pkg/ocibundle/native/bundle_linux.go

- sylabs/singularity# 1871
which fixed
- sylabs/singularity# 1854
> There was a considerable amount of code duplicated between:
> 
> * The new `pkg/ocibundle/native` package.
> * The existing `internal/pkg/build/sources` OCI portions.
> 
> This PR aims to de-duplicate by moving the common OCI fetch and extraction implementation into `internal/pkg/build/oci`.
> 
> Note that function signatures remain ugly and long. I have deliberately avoided adding config structs, or heavily rewriting into a struct/ functional options pattern, to keep the changes relatively easy to read. We may want to improve the code structure in future.
> 
> There is also a general lack of test coverage below the e2e level. The e2e coverage is pretty good, …

chore: refactor OCI fetch/extraction code, from sylabs 1871

---

e2e/actions/oci.go

- sylabs/singularity# 1873
> Instead of counting the mounts, compare the full mount table before and after execution. The assert.Equal will produce a nice diff if they don't match, easing troubleshooting.
> 
> Cherry-picked from the WIP sylabs/singularity# 1838 to simplify that ongoing PR.

e2e: In actionOCiOverlayTeardown, show mount table differences, from sylabs 1873

---

LICENSE_DEPENDENCIES.md
e2e/actions/actions.go
e2e/actions/oci.go
e2e/docker/docker.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

- sylabs/singularity# 1597
> _NOTE: This PR is a continuation of sylabs/singularity# 1531. See additional discussion there._
> 
> The way the Passwd() utility-function (internal/pkg/util/fs/files/passwd.go:22) worked until now, it was only able to append a new line to what it got as input (from the base layer).
> 
> This meant that, for example, to override the homedir of a regular user, we would simply add a modified line (with the custom homedir) to the in-container /etc/passwd; but to override the homedir of root (when running singularity itself as root, or when running with `--fakeroot`), we couldn't do that – since there was already a "root" line in the base layer's /etc/passwd – and we resorted to an entirely different method, …

Revamp passwd utility function, from sylabs 1597

---

internal/pkg/runtime/launcher/oci/launcher_linux.go
pkg/ocibundle/native/bundle_linux.go

- sylabs/singularity# 1872
which fixed
- sylabs/singularity# 1855
> In Singularity's native mode, we assemble the runtime representation of the container's rootfs under a tmpfs mounted on buildcfg.SESSIONDIR. The pristine rootfs, whether from a SIF file or an OCI source image extracted to a directory, is mounted into the tmpfs before other overlays, customised files, host mounts etc. are layered over it.
> 
> The location of buildcfg.SESSIONDIR is set when SingularityCE is compiled. It is documented that it needs to be on a local filesystem. Using a tmpfs mount over a local fs SESSIONDIR avoids potential issues with mounts over network file systems etc. The OCI mode is currently vulnerable to issues as it creates the runtime bundle …

oci: create runtime bundle within buildcfg.SESSIONDIR tmpfs, from sylabs 1872

---

CHANGELOG.md
cmd/internal/cli/cache_clean_linux.go
cmd/internal/cli/cache_list_linux.go
internal/pkg/cache/cache.go

- sylabs/singularity# 1876
which fixed
- sylabs/singularity# 1857
> Add an oci-sif cache type, that will be used to store 1:1 conversions of OCI source images (e.g. docker://) into oci-sif format.
> 
> Refactor the help display for cache types, to list types programatically. This corrects and avoids incorrect/incomplete help information.

cache: Add oci-sif cache type, from sylabs 1876

---

cmd/internal/cli/actions.go
cmd/internal/cli/apptainer.go
internal/pkg/util/rootless/rootless.go

- sylabs/singularity# 1883
> When we need to enter a mount or user namespace to begin oci-mode operation, do so as early as possible.
> 
> The CLI code has a lot of logic in it, much of which may run twice if we re-exec in `launchContainer`. This code may also cause side effects.
> 
> Re-execing much earlier, at the root command's `PersistentPreRun`, avoids these issues.

oci: re-exec as early as possible, from sylabs 1883

---

CHANGELOG.md
LICENSE_DEPENDENCIES.md
cmd/internal/cli/pull.go
e2e/internal/e2e/image.go
e2e/pull/pull.go
go.mod
go.sum
internal/pkg/client/oci/ocisif.go
internal/pkg/client/oci/pull.go
internal/pkg/client/oci/sif.go

- sylabs/singularity# 1878
which fixed
- sylabs/singularity# 1859
> Add a new flag `--oci` to the `pull` command.
> 
> When `pull --oci` is used to pull from an OCI source, create an OCI-SIF image.
> 
> First, we use existing code built around containers/image to create a temporary oci layout directory holding the source image. This step will use the existing OCI blob cache.
> 
> We modify the temporary oci layout using sylabs/oci-tools, to squash the layers down to one, and convert from .tar.gz to squashfs format.
> 
> _Note r.e. test coverage:_
> 
> There is coverage of the code added and amended here, in `E2E/PULL` and because a `pull --oci` is now used to generate the image used for most OCI mode e2e tests.
> 
> However, it …

oci: Support pull --oci to OCI-SIF, from sylabs 1878

---

CHANGELOG.md
cmd/internal/cli/actions.go
e2e/actions/oci.go
internal/pkg/build/oci/fetch.go
internal/pkg/client/oci/ocisif.go
internal/pkg/client/oci/pull.go

- sylabs/singularity# 1882
which fixed
- sylabs/singularity# 1860
> When a direct URI is provided for `run/shell/exec` in `--oci` mode, perform a pull through the cache to obtain an OCI-SIF image, and execute this.
> 
> `--oci` mode is no longer limited to OCI URIs or `oci-sif` as valid sources. If an `oci-sif` can be retrieved from the library/shub/oras/http/https protocols it can be run.
> 
> At this point, http/https is trivial to e2e-test so can be supported.
> 
> The barriers for the other protocols are primarily around pushing an image, rather than pulling. When push of oci-sif is supported and tested in follow-up PRs, then we can list the protocols as supported.
> 
> This PR also incorporates some small fixes for issues …

oci: switch direct run/shell/exec from URI to oci-sif flow, from sylabs 1882

---

CHANGELOG.md
e2e/actions/oci.go
e2e/internal/e2e/env.go
e2e/internal/e2e/image.go
e2e/pull/pull.go
e2e/push/push.go
e2e/suite.go

- sylabs/singularity# 1884
which fixed
- sylabs/singularity# 1863
- sylabs/singularity# 1864
> Add e2e tests for push / pull / run against oras URIs, with OCI-SIF images.
> 
> This is a testing-only change. Because our oras code will push/pull any SIF image, it is working as of sylabs/singularity# 1882.

e2e: oci: oras push/pull/run, from sylabs 1884

---

internal/pkg/client/oras/oras.go
internal/pkg/runtime/launcher/native/launcher_linux.go
pkg/image/image.go
pkg/image/ocisif.go
pkg/image/ocisif_test.go
pkg/image/sif.go
pkg/image/sif_test.go

This pulls in sylabs PRs
- sylabs/singularity# 1886
- sylabs/singularity# 1891
which fixed
- sylabs/singularity# 1890
The original PR descriptions were:
> Add a minimal oci-sif image type to pkg/image, that does not implement any functionality other than oci-sif detection.
> 
> Ensure oci-sif detected as oci-sif, and are not detected as the existing sif type.
> 
> Modify the native launcher to return a more friendly error if a user attempts to run an oci-sif with it.
> 
> Prep work for sylabs/singularity# 1861
> 
> Example...
> 
> ```
> $ singularity run alpine_latest.sif 
> FATAL:   While checking image: native runtime does not support OCI-SIF images, use --oci mode
> ```
> After sylabs/singularity# 1886 the check for a vaild SIF image must be relaxed to include `image.OCISIF`.
> 
> …

pkg/image: Add minimal oci-sif type, from sylabs 1886

---

CHANGELOG.md
e2e/oci/oci.go
internal/pkg/util/fs/squashfs/squashfs.go
pkg/ocibundle/ocisif/bundle_linux.go
pkg/ocibundle/sif/bundle_linux.go

- sylabs/singularity# 1904
which fixed
- sylabs/singularity# 1897
> The singularity SIF -> OCI bundle mount was previously performed with a kernel squashfs mount.
> 
> We will be using `pkg/ocibundle/sif` as the basis of `--oci` mode execution of singularity SIF (non oci-sif) images.
> 
> Switch the mount to use squashfuse for consistency. `--oci` mode does not perform kernel mounts from SIF.

oci: switch `oci mount` to squashfuse, from sylabs 1904

---

cmd/internal/cli/actions.go
cmd/internal/cli/checkpoint.go
cmd/internal/cli/instance_actions_linux.go
e2e/actions/oci.go
internal/pkg/runtime/launcher/launcher.go
internal/pkg/runtime/launcher/launcher_test.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go
pkg/image/image.go
pkg/image/sif.go
pkg/ocibundle/sif/bundle_linux.go
pkg/ocibundle/sif/bundle_linux_test.go

- sylabs/singularity# 1906
which fixed
- sylabs/singularity# 1899
> Implement `ImageSpec()` for `ocibundle/sif`, so that it returns a usable OCI image spec. Use the OCI image config embedded in the SIF file, if it is present.
> 
> Implement basic execution of non-oci SIF images in `--oci` mode. This is acheived by calling the `/singularity.d/action/*` scripts inside the non-oci SIF container. Generation of container process args including the action script has been moved to a struct `ExecParams` in the `launcher` package, so that it can be called from the OCI launcher when needed.
> 
> e2e testing is currently minimal. As work proceeds to wire-up native runtime compatible env handling, and have the option to run in non- `--compat`, …

oci: Execute non-oci SIF in --oci mode, from sylabs 1906

---

LICENSE_THIRD_PARTY.md
cmd/internal/cli/pull.go
cmd/internal/cli/push.go
e2e/push/push.go
go.mod
internal/pkg/client/oci/auth.go
internal/pkg/client/oci/ocisif.go
internal/pkg/client/oci/push.go

- sylabs/singularity# 1917
which fixed
- sylabs/singularity# 1914
> Allow `singularity push` to push OCI-SIF images (only) to OCI registries specified by a `docker://` URI.
> 
> This code uses go-containerregistry rather than containers/image so that the implementation is simple to couple to the sylabs/oci-tools package.

push: OCI-SIF to docker:// OCI registries, from sylabs 1917

---

internal/pkg/client/oci/auth.go

- sylabs/singularity# 1923
> Oversight in review / rebase to merge sylabs/singularity# 1917

fix: Remove Warningf of credential in oci-sif docker:// push, from sylabs 1923

---

CHANGELOG.md
e2e/internal/e2e/env.go
e2e/internal/e2e/image.go
e2e/pull/pull.go
e2e/suite.go
internal/pkg/client/oci/ocisif.go

- sylabs/singularity# 1926
which fixed
- sylabs/singularity# 1915
> If `singularity pull --oci` is used against an OCI registry `docker://` reference, and the reference is a single-layer squashfs image, pull it into an OCI-SIF without any mutation.
> 
> This is the mirror-image operation of sylabs/singularity# 1917, allowing OCI-SIF images pushed with the code in sylabs/singularity# 1917 to be pulled.
> 
> Note that the pull e2e tests have been re-arranged / re-named. This is to keep all the `library://` `oras://` `docker://` tests next to eachother.... and in an attempt to make it more obvious what is testing what.

pull: Pull previously pushed OCI-SIF from OCI registry (docker://), from sylabs 1926

---

e2e/env/regressions.go
go.mod
go.sum
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/oci/process_linux_test.go
internal/pkg/util/env/env.go
internal/pkg/util/shell/interpreter/interpreter.go
internal/pkg/util/shell/interpreter/interpreter_test.go

This pulls in apptainer/apptainer# 1452 into the oci-action branch and adds one more oci-specific change from sylabs/singularity# 1789.  It's done as a separate PR here instead of waiting for a rebase so that extra oci change doesn't get forgotten.

chore(deps): Bump mvdan.cc/sh/v3 from 3.6.1-0.20221221181323-d3feb15bed3a to 3.7.0

---

.golangci.yml
cmd/internal/cli/actions.go
cmd/internal/cli/inspect.go
docs/remote.go
e2e/cgroups/cgroups.go
e2e/config/config.go
e2e/internal/e2e/imageverify.go
internal/app/apptainer/plugin_list_linux.go
internal/app/starter/master_linux_test.go
internal/pkg/build/sources/conveyorPacker_oci.go
internal/pkg/plugin/meta.go
internal/pkg/runtime/engine/engine_linux.go
internal/pkg/signature/verify_ocsp.go
internal/pkg/test/tool/doc.go
internal/pkg/util/crypt/crypt_dev.go
internal/pkg/util/interactive/interactive_test.go
pkg/util/apptainerconf/config.go
pkg/util/capabilities/process_linux.go
pkg/util/fs/proc/proc_linux_test.go

Enable the `dupword` linter in golangci-lint, and perform fixes / add `nolint:` directives, as appropriate, in code.

lint: enable dupword + corresponding fixes, from sylabs 2062

---

.golangci.yml
internal/pkg/runtime/engine/apptainer/container_linux.go
internal/pkg/syecl/syecl.go

* sylabs/singularity#2064
> Enable the `exportloopref` linter in golangci-lint, and perform fixes, as appropriate, in code.

lint: enable exportloopref + corresponding fixes

---

.golangci.yml
cmd/internal/cli/apptainer_test.go
docs/remote.go
e2e/internal/e2e/const.go
e2e/internal/e2e/docker.go
e2e/internal/e2e/docker_auth_server.go
internal/app/apptainer/oci_delete_linux.go
internal/pkg/build/sources/conveyorPacker_oci.go
internal/pkg/build/sources/conveyorPacker_zypper.go
internal/pkg/image/packer/gocryptfs.go
internal/pkg/remote/credential/login_handler.go
internal/pkg/remote/endpoint/keyserver.go
internal/pkg/remote/remote_test.go
internal/pkg/runtime/engine/apptainer/container_linux.go
internal/pkg/runtime/engine/oci/process_linux.go
internal/pkg/util/auth/auth_test.go
internal/pkg/util/fs/mount/system_linux.go
pkg/build/types/definition.go
pkg/util/unix/socket_test.go

This pulls in 
* sylabs 2066
Original PR description:
> Enable the `gosec` linter in golangci-lint, and perform fixes / add `#nosec` directives, as appropriate, in code.
> 
> Also adds three specific `gosec` rules to golangci-lint "exclude" list due to large number of false positives.

lint: enable gosec + corresponding fixes, from sylabs 2066

---

.golangci.yml
e2e/cache/cache.go
internal/pkg/build/files/files.go
internal/pkg/checkpoint/dmtcp/checkpoint.go
internal/pkg/checkpoint/dmtcp/dmtcp.go
internal/pkg/plugin/binary.go
internal/pkg/runtime/engine/config/oci/generate/generate.go
pkg/build/types/parser/deffile.go
pkg/image/sif_test.go
pkg/runtime/engine/apptainer/config/bind.go

This pulls in
* sylabs/singularity# 2068
Original PR description:
> 
> Enable the `prealloc` linter in golangci-lint, and perform fixes, as appropriate, in code.

lint: enable prealloc + corresponding fixes, from sylabs 2068
